#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	2) admin:///home/erik/bin/clear-ram-cache ;;
esac

free -h | awk '/^Mem:/ {print $3 "(" $6 ")/" $2}'
