#!/usr/bin/env bash

alarmThreshold=${_CPU_TEMP_ALARM_THRESHOLD:-70}
colorstr=$BLOCK_TEXT_COLOR_NORMAL
cpuCoreLabel=${BLOCK_INSTANCE:-"Core 0"}
coreNumber=$(echo $cpuCoreLabel | awk '{print $2}')
critThreshold=${_CPU_TEMP_CRIT_THRESHOLD:-82}
tempstr=""


if [ "$1" = "-h" ] ; then
	echo "cpu-core-temp <core_number> <alarm_threshold>"
	exit 0
fi

#case $BLOCK_BUTTON in
	#1) echo "Left click action" ;;
	#2) echo "Right click action" ;;
#esac

# FIXME How to consolidate all these repeated commands into one??
case "$coreNumber" in
	"0") tempstr="$(sensors | awk '/^Core 0/ {print $3}' | sed -E 's/(\+|\.0)//g')";;
	"1") tempstr="$(sensors | awk '/^Core 1/ {print $3}' | sed -E 's/(\+|\.0)//g')";;
	"2") tempstr="$(sensors | awk '/^Core 2/ {print $3}' | sed -E 's/(\+|\.0)//g')";;
	"3") tempstr="$(sensors | awk '/^Core 3/ {print $3}' | sed -E 's/(\+|\.0)//g')";;
	*) echo "Unkown core number $coreNumber"; exit 1 ;;
esac

tempnum="$(echo $tempstr | grep -oE '^[0-9]+')"

if [ "$tempnum" -ge "$alarmThreshold" ] ; then
	colorstr=$BLOCK_TEXT_COLOR_DEGRADED
fi

printf '{"full_text":"%s","color":"%s"}\n' "$tempstr" "$colorstr"

if [ "$tempnum" -ge "$critThreshold" ] ; then
	exit 33 #urgent
fi

exit 1
