#!/bin/sh

# FIXME is there a better way to toggle between
# where to read the constants files???
if [ -e ../block-constants ] ; then
	. ../block-constants/block-constants
else
	. ~/bin/i3blocks/block-constants
fi

alarmThreshold=${_CPU_TEMP_ALARM_THRESHOLD:-70}
colorstr=$BLOCK_TEXT_COLOR_NORMAL
coreNumber=${_CPU_TARGET_CORE:-0}
critThreshold=${_CPU_TEMP_CRIT_THRESHOLD:-82}
tempstr=""


if [ "$1" = "-h" ] ; then
	echo "cpu-core-temp <core_number> <alarm_threshold>"
	exit 0
fi

#case $BLOCK_BUTTON in
	#1) echo "Left click action" ;;
	#2) echo "Right click action" ;;
#esac

case "$coreNumber" in
	"0") tempstr="$(sensors | awk '/^Core 0/ {print $3}' | sed -E 's/(\+|\.0)//g')";;
	"1") tempstr="$(sensors | awk '/^Core 1/ {print $3}' | sed -E 's/(\+|\.0)//g')";;
	"2") tempstr="$(sensors | awk '/^Core 2/ {print $3}' | sed -E 's/(\+|\.0)//g')";;
	"3") tempstr="$(sensors | awk '/^Core 3/ {print $3}' | sed -E 's/(\+|\.0)//g')";;
	*) echo "Unkown core number $coreNumber"; exit 1 ;;
esac

tempnum="$(echo $tempstr | grep -oE '^[0-9]+')"

if [ "$tempnum" -gt "$alarmThreshold" ] || [ $tempnum = $alarmThreshold ] ; then
	colorstr=$BLOCK_TEXT_COLOR_BAD
fi

printf '{"full_text":"%s","color":"%s"}\n' "$tempstr" "$colorstr"

if [ "$tempnum" -gt "$critThreshold" ] || [ $tempnum = $critThreshold ] ; then
	exit 33 #urgent
fi

exit 1
