#!/bin/sh

acstat="$(acpi --ac-adapter | awk '/^Adapter 0:/ {print $3}')"
batstatPrimary="$(acpi --battery | awk '/^Battery 0:/ {print}')"
batstatSecondary="$(acpi --battery | awk '/^Battery 1:/ {print}')"

if [ "$batstatSecondary" != "" ]; then
	batstat="$batstatSecondary"
else
	batstat="$batstatPrimary"
fi

batmode="$(echo $batstat | awk '{print $3}' | sed 's/,//')"
batlvl="$(echo $batstat | grep -oE "[0-9]?{2}[0-9]%")"
battime="$(echo $batstat | awk '{print $5}')"
result="--"

# Possible values for acpi --battery
# Battery 0: Not charging, 0%, rate information unavailable
# Battery 1: Charging, 76%, 00:27:06 until charged


if [ "$acstat" = 'on-line' ] ; then
	if [ "$batstat" = '' ] || [ "$batlvl" = "0%" ] ; then
		result="AC" 
	elif [ "$batlvl" = "100%" ] ; then
		result="BAT-F"
	else
		result="BAT-C $batlvl $battime"
	fi
else
	if [ "$batmode" = 'Discharging' ] ; then
		result="BAT-D $batlvl"
	fi
fi

#case $BLOCK_BUTTON in
	#1) echo "Left click action" ;;
	#2) echo "Right click action" ;;
#esac
if [ "$1" = '-V' ] ; then
	echo "acpi -a: $acstat"
	echo "acpi -b: $batstat"
	echo "battery mode: $batmode"
	echo "battery level: $batlvl"
	echo "battery time: $battime"
fi

echo "$result"
